---
# tasks file for consul

- name: upgrade package in debian family oses
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - upgrade-package

- name: upgrade package in redhat family oses
  yum:
    name: "*"
    state: latest
  when:
    - ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CentOS'

- name: download pre-requisite package for debian family oses
  apt:
    name: "{{ item }}"
    state: latest
    force_apt_get: yes
  with_items:
    - unzip
  when:
    -  ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - setup-prerequisite

- name: download pre-requisite package for redhat family oses
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
  when:
    -  ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - setup-prerequisite

- name: create required directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/consul
    - /var/lib/consul
  tags:
    - create-dir

- name: download consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
  tags:
    - download-consul

- name: extract consul
  unarchive:
    src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/
    remote_src: yes
  tags:
    - extract-consul

- name: move consul binary
  copy:
    src: /tmp/consul
    dest: /usr/local/bin/consul
    mode: 0755
    remote_src: yes
  tags:
    - move-consul-binary